server:
  port: 8080
  context-path: /springboot

person:
  name: zhangsan
  age: 18
  content: ${person.name} is ${person.age}

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
application.message: Hello springboot.
